var searchData=
[
  ['field_0',['field',['../namespacenew_alternative_1_1field.html',1,'newAlternative']]],
  ['newalternative_1',['newAlternative',['../namespacenew_alternative.html',1,'']]],
  ['notallnumbersarepossibleexeption_2',['NotAllNumbersArePossibleExeption',['../class_exeptions_1_1_not_all_numbers_are_possible_exeption.html',1,'Exeptions.NotAllNumbersArePossibleExeption'],['../class_exeptions_1_1_not_all_numbers_are_possible_exeption.html#ad395fd4a79d0bd384e1df0e9a4b64ba9',1,'Exeptions.NotAllNumbersArePossibleExeption.NotAllNumbersArePossibleExeption()']]],
  ['notallnumbersarepossibleexeption_2ejava_3',['NotAllNumbersArePossibleExeption.java',['../_not_all_numbers_are_possible_exeption_8java.html',1,'']]],
  ['numberfield_4',['NumberField',['../class_old_1_1_number_field.html#ae9b33dc54681423c021be38b4cb33fa3',1,'Old.NumberField.NumberField(int number)'],['../class_old_1_1_number_field.html#a752024e8b64c70f57507d16afe66310c',1,'Old.NumberField.NumberField()'],['../class_old_1_1_number_field.html',1,'Old.NumberField']]],
  ['numberfield_2ejava_5',['NumberField.java',['../_number_field_8java.html',1,'']]],
  ['numbergroup_6',['NumberGroup',['../class_fork_join_alternative_1_1_number_group.html',1,'ForkJoinAlternative.NumberGroup'],['../classnew_alternative_1_1_number_group.html',1,'newAlternative.NumberGroup'],['../class_fork_join_alternative_1_1_number_group.html#a2beca6b8dff5f5d84c1187741dbd09c8',1,'ForkJoinAlternative.NumberGroup.NumberGroup(Field[] matrix, ExecutorService executorService)'],['../class_fork_join_alternative_1_1_number_group.html#a427672570d87c550fc56b68da08a57c3',1,'ForkJoinAlternative.NumberGroup.NumberGroup(int[] matrix, ExecutorService executorService)'],['../classnew_alternative_1_1_number_group.html#a8416e312d08632e26dae921335dc1a2b',1,'newAlternative.NumberGroup.NumberGroup(Field[] matrix)'],['../classnew_alternative_1_1_number_group.html#a4db3a21f83edebb6688995e486d2c08e',1,'newAlternative.NumberGroup.NumberGroup(int[] matrix)'],['../class_stuff_1_1_number_group.html#a56e6e15c5f5ded64a8c2f5c79b7c6023',1,'Stuff.NumberGroup.NumberGroup(Field[] matrix)'],['../class_stuff_1_1_number_group.html#aede083bc889e2f3440b109b4968ee033',1,'Stuff.NumberGroup.NumberGroup(Collection&lt; Field &gt; collection)'],['../class_stuff_1_1_number_group.html#a3967bc7d829c5dd4fc80d09cee07edf8',1,'Stuff.NumberGroup.NumberGroup(int[] matrix)'],['../class_stuff_1_1_number_group.html',1,'Stuff.NumberGroup']]],
  ['numbergroup_2ejava_7',['NumberGroup.java',['../_fork_join_alternative_2_number_group_8java.html',1,'(Global Namespace)'],['../new_alternative_2_number_group_8java.html',1,'(Global Namespace)'],['../_stuff_2_number_group_8java.html',1,'(Global Namespace)']]]
];
